### ISSUE TITLE
Introduce an option to reverse hotbar scrolling

### ISSUE THREAD

**Issue by hamarb123** [hamarb123/MCMacOSInputFixes#1]
Since this mod changes the hotbar scrolling to be consistent with the rest of macOS, it ends up scrolling in the other direction. Some people are not used to this and would like an option to change the hotbar scrolling direction. This will be introduced in an upcoming version, you can add notifications to this issue to stay up-to-date about its progress.

**Comment by CreepyHobo** [comment]
GameParrot did some work with these Minecraft/macOS issues before, maybe you can collaborate?

**Comment by hamarb123** [comment]
@GameParrot 's ones require replacing native binaries, whereas mine doesn't (which is very intentional). Maybe we could recommend each other's mods and he could remove his fix for MC-121772 so it doesn't interact badly with mine (which it probably doesn't, idk). We also may be able to incorporate his other mouse fix into this mod (MC-145948), but I've never experienced this so I wouldn't know if I'd actually fixed it or not. Also I just discovered MC-122296 which my mod fixes too lol, I'll have to add that to the list.

**Comment by CreepyHobo** [comment]
I'm strictly a user, to say my knowledge of programming is minuscule would be giving me credit. That said, GameParrot's mod did fix, I believe, 6 MC-XXXXXX issues, would it be possible to put all of those in your mod?

**Comment by hamarb123** [comment]
The issue is that my mod is done through java and a custom native library, whereas his modifies preexisting native files, meaning the fixes are quite different.

**Comment by hamarb123** [comment]
Implemented in version 1.1
