### ISSUE TITLE
[Incompatibility] Condensed Creative mod - Unable to scroll smoothly

### ISSUE THREAD

**Issue by Aces-and-Jacks** [hamarb123/MCMacOSInputFixes#10]
It works with the condensed creative mod but I'm unable to scroll correctly

https://mclo.gs/gBYRZSB

**Comment by hamarb123** [comment]
Can you try it with the discrete scroll option from the base game enabled? This seemed to help on my computer. I will need to fix the trackpad with discrete scrolling probably, but can you just check that you can actually scroll with that option enabled.

**Comment by Aces-and-Jacks** [comment]
yeah discrete scrolling works

**Comment by hamarb123** [comment]
Todo: make trackpad scrolling work correctly with discrete scrolling enabled.

**Comment by Aces-and-Jacks** [comment]
By correctly do you mean where scrolling doesn't zoom through the inventory?

**Comment by hamarb123** [comment]
(I added this with an edit :) )
It seems the code still exists and is used, just not in 'interfaces', so I'll fix it by making it be used in interfaces also when discrete scroll is enabled.

So yeah basically.

**Comment by Aces-and-Jacks** [comment]
ah ok. And by interfaces you mean screens like the inventory screen, and/or anything that has scrolling?

**Comment by hamarb123** [comment]
Yes, anything that's not scrolling on the hotbar basically, for it to be fixed without this workaround would require the other mod to accept fractional scrolling.

**Comment by hamarb123** [comment]
Fixed in 1.5
