### ISSUE TITLE
Allow distribution on Curseforge

### ISSUE THREAD

**Issue by Madis0** [hamarb123/MCMacOSInputFixes#12]
It looks like you've toggled this off on Curseforge project's settings:

![Screenshot_20230421_174925](https://user-images.githubusercontent.com/8611110/233666719-3a434b23-e66b-4534-a667-e178a5762b8f.png)

Could you toggle it on again? It allows users to download your mod on external launchers like GDLauncher, which especially matters on modpacks (that would otherwise be partial).

**Comment by hamarb123** [comment]
Is there a reason you can't use modrinth? Consider also that massive mods like Iris and Sodium aren't even on CF anymore. The reason I have it on CF is because it gets more downloads than modrinth. If everyone just used modrinth (since it's better), then I wouldn't worry about CF at all.

**Comment by Madis0** [comment]
As a user, of course I can. 
As a modpack dev, I do use Modrinth as well, but would also like to give my users choices on what launcher to use.

The problem with this toggle is that it essentially locks CurseForge modpacks to using CurseForge launcher, because other launchers would only get a partial pack. But as you said, Sodium and Iris are currently no longer available on such launchers as well, so it is up to you.
