### ISSUE TITLE
Incompat with MinecraftClientGoBrr

### ISSUE THREAD

**Issue by Tempest-5ky** [hamarb123/MCMacOSInputFixes#14]
Crash on startup, seems to be an incompat with this mod?: https://modrinth.com/mod/minecraftclientgobrrr

Crashlog: https://mclo.gs/ZGhriLa

if it's their fault lmk and i'll post the issue there instead!

**Comment by hamarb123** [comment]
@Zensonaton it seems like `MinecraftClient.window` doesn't get set by your mod [here](https://github.com/Zensonaton/MinecraftClientGobrrr/blob/main/src/main/java/com/zensonaton/minecraftclientgobrrr/mixin/MinecraftClientMixin.java#L40).

Is there a reason you are not just shadowing the `window` field and setting it? You seem to have created your own window field instead.

**Comment by Zensonaton** [comment]
> @Zensonaton it seems like `MinecraftClient.window` doesn't get set by your mod [here](https://github.com/Zensonaton/MinecraftClientGobrrr/blob/main/src/main/java/com/zensonaton/minecraftclientgobrrr/mixin/MinecraftClientMixin.java#L40).
> 
> Is there a reason you are not just shadowing the `window` field and setting it? You seem to have created your own window field instead.

I did this because I thought that there is no chance that `window` field with 'early' window would be used anywhere, so this is why I did this.

I'll fix that in the next update if I won't get into any troubles.

**Comment by Zensonaton** [comment]
I've made the fix locally, I'm going to push those changes to my repo soon.

I think that you should mark `1.0` version of my mod in your [`fabric.mod.json`](https://github.com/hamarb123/MCMacOSInputFixes/blob/main/src/main/resources/fabric.mod.json) as 'breaks':
```java
"breaks": {
    "minecraftclientgobrrr": "<=1.0"
}
```
