### ISSUE TITLE
1.20.1 ETA?

### ISSUE THREAD

**Issue by SpektacleFR** [hamarb123/MCMacOSInputFixes#16]
You probably get this question asked a lot, but is there any ETA for 1.20.1?  Minecraft is quite literally unplayable without this for me :)

**Comment by hamarb123** [comment]
The mod should work on 1.20.1, which version did you try it with?

**Comment by SpektacleFR** [comment]
My bad, I had previously downloaded this mod via Modrinth (with ATLauncher), and at the time I suppose there was no "official" 1.20.1 release on the page.  Downloaded from here and manually installed, everything worked great.  Sorry for confusion!
