### ISSUE TITLE
CTRL + Tab to show tablist

### ISSUE THREAD

**Issue by AuthenTiiq** [hamarb123/MCMacOSInputFixes#17]
Hello,

Is it possible to display the Tablist when CTRL Tab is pressed?
I usually hold CTRL to run and when I want to check tablist I can not.

Thanks !

**Comment by hamarb123** [comment]
Macbook keyboards (at least any I've tried) physically do not support sending the signal for these keys at the same time. I cannot do anything about this, you would have to remap one of them to get this to work.

**Comment by hamarb123** [comment]
Wait, I've misremembered what keys that happens for, I will investigate this further

**Comment by hamarb123** [comment]
I've developed a fix for this locally, which also fixes the same bug for escape. It will be in the next version, will notify when releasing.

**Comment by hamarb123** [comment]
Fixed in 1.6
