### ISSUE TITLE
Broken in snapshot 24w20a

### ISSUE THREAD

**Issue by zumbiepig** [hamarb123/MCMacOSInputFixes#27]
I clicked the `Controls` button, and minecraft crashed. Here are the logs: https://mclo.gs/umDojfb

**Comment by hamarb123** [comment]
Thanks, I will look into this when I'm able.
If I don't look into this within ~5 days, please remind me as I may have forgotten.

**Comment by hamarb123** [comment]
I won't look at that as a part of this. Porting to forge would require a rewrite basically for forge, and 1.8.9 is also quite different to 1.13 in that it uses a different major version of lwjgl, which the input probably works quite different on (therefore, it would definitely require a lot of changes on top of that). Whereas, with the snapshot, it is likely only a minor change from existing 1.20 code.

**Comment by hamarb123** [comment]
Thanks for reminding me, I will see if I have time on the weekend

**Comment by hamarb123** [comment]
I've fixed it in a commit - I will release the actual 1.7 version when 1.21 comes out since I don't support snapshots

**Comment by caoimhebyrne** [comment]
@hamarb123 1.21 is out, will it be released on Modrinth?

**Comment by hamarb123** [comment]
It is now released
