### ISSUE TITLE
Crash when trying to open the controls screen on 1.21

### ISSUE THREAD

**Issue by hw2007** [hamarb123/MCMacOSInputFixes#29]
As of MInecraft 1.21.0, the game crashes when I try to open the controls menu in the game settings.
I have attached the crash report Minecraft gave me down below. 

[crash-2024-06-14_16.21.45-client.txt](https://github.com/user-attachments/files/15844398/crash-2024-06-14_16.21.45-client.txt)

**Comment by hamarb123** [comment]
Released - should be available on CurseForge and Modrinth soon.

**Comment by hw2007** [comment]
> Released - should be available on CurseForge and Modrinth soon.

Man, I love small projects like this... I think that was the fastest I've ever seen a report of mine get resolved! Thanks!

**Comment by WERDXZ** [comment]
Same here, just found it:) Thank you
