### ISSUE TITLE
Crash when accessing settings menu on 1.19.3

### ISSUE THREAD

**Issue by cadenkriese** [hamarb123/MCMacOSInputFixes#7]
This crash occurred while accessing the mouse settings menu on 1.19.3; it did not occur on 1.19.2. 

[crash-2022-12-17_09.22.55-client.txt](https://github.com/hamarb123/MCMacOSInputFixes/files/10252135/crash-2022-12-17_09.22.55-client.txt)

**Comment by hamarb123** [comment]
Thanks, I have already developed a 1.19.3 version, but I'm yet to upload it since I haven't tested it thoroughly yet, but it shouldn't be too long until I do. I'll let you know once it's uploaded.

**Comment by hamarb123** [comment]
I've updated the mod, not sure how long it will take for it to be available on CurseForge, but it should be available here and on Modrinth.

**Comment by cadenkriese** [comment]
That was quick. Much appreciated!
